
default_platform(:ios)

platform :ios do

  ### Helper Defs ###

  def build_automatic
    clear_derived_data
    get_provisioning_profile(
      adhoc: true,
      api_key_path: "fastlane/578LND8DV7.json",
      filename: "../re-jord-iOS/Tuist/Signing/ReJord.Debug.mobileprovision"
    )
    build_ios_app(
      export_method: "ad-hoc",
      configuration: "Debug",
      silent: false
    )
  end


  ### Lanes ###
  
  lane :build_current do
    build_automatic
  end

  lane :testflight_test do
    # get latest number from Testflight
    latest_build_number=latest_testflight_build_number(
      api_key_path: "fastlane/578LND8DV7.json"
    )
    # build app
    build_automatic
    # upload to Testflight
    pilot(api_key_path: "fastlane/578LND8DV7.json")
  end





end
