# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install SSH key    
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: lsal
      run: ls -al
    
    - name: ../
      run: cd ../ && ls -al

    - name: Navigate to repository root
      run: cd $GITHUB_WORKSPACE && ls -al
    
    - name: Testflight Upload
      run: fastlane testflight_upload
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}